services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - elastic
    deploy:
      resources:
        limits: { memory: 1500M, cpus: "1.2" }
        reservations:
          memory: 1g
          cpus: "0.7"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
        reservations:
          memory: 400m
          cpus: "0.3"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: h2-file
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.8"
        reservations:
          memory: 700m
          cpus: "0.5"

volumes:
  elasticsearch-data:
    driver: local
  keycloak-data:
    driver: local

networks:
  elastic:
    driver: bridge
